  tokenizer = Tokenizer() ...
  remover= StopWordsRemover() ...
  hashingTF = HashingTF().setNumFeatures(1000) ...
  idf = IDF() ...
  lr = LinearSVC(labelCol="label", featuresCol="features", ...)
  pipeline=Pipeline(stages=[tokenizer, remover, hashingTF, idf, lr])